// world_types.h
// Primitive types and named constants used throughout DaedalusWorld.
//
// Keep this header dependency-free (includes only core/types.h) so it
// can be used by all world headers without introducing transitive deps.

#pragma once

#include "daedalus/core/types.h"

#include <cstdint>

namespace daedalus::world
{

// ─── SectorId ─────────────────────────────────────────────────────────────────
// An index into WorldMapData::sectors. Value INVALID_SECTOR_ID indicates "no
// sector" (e.g. a non-portal wall, an out-of-bounds query result).

using SectorId = u32;

constexpr SectorId INVALID_SECTOR_ID = 0xFFFF'FFFFu;

// ─── Portal traversal depth limit ────────────────────────────────────────────
// Maximum recursive portal depth per frame. Prevents traversal cycles in
// degenerate maps and bounds worst-case CPU cost.

constexpr u32 MAX_PORTAL_DEPTH = 32u;

// ─── WallFlags ────────────────────────────────────────────────────────────────
// Bit-field describing per-wall properties.

enum class WallFlags : u32
{
    None        = 0,
    TwoSided    = 1u << 0,  ///< Render the back face as well (glass, grates).
    Blocking    = 1u << 1,  ///< Solid collision wall; player / NPCs cannot pass.
    Climbable   = 1u << 2,  ///< Player can mantle / climb this wall.
    TriggerZone = 1u << 3,  ///< Generates a trigger event when crossed.
    Invisible   = 1u << 4,  ///< Wall exists for collision but is not rendered.
    Mirror      = 1u << 5,  ///< Planar mirror surface; rendered via MirrorDraw pre-pass.
    // ── Phase 1F additions ────────────────────────────────────────────────────
    NoPhysics   = 1u << 6,  ///< Wall has no collision shape (decorative surface,
                            ///< background panel, non-blocking architectural detail).
};

[[nodiscard]] inline constexpr WallFlags operator|(WallFlags a, WallFlags b) noexcept
{
    return static_cast<WallFlags>(static_cast<u32>(a) | static_cast<u32>(b));
}

[[nodiscard]] inline constexpr WallFlags operator&(WallFlags a, WallFlags b) noexcept
{
    return static_cast<WallFlags>(static_cast<u32>(a) & static_cast<u32>(b));
}

[[nodiscard]] inline constexpr bool hasFlag(WallFlags flags, WallFlags test) noexcept
{
    return (flags & test) != WallFlags::None;
}

// Bit-field operators for WallFlags |
[[nodiscard]] inline constexpr WallFlags operator~(WallFlags a) noexcept
{
    return static_cast<WallFlags>(~static_cast<u32>(a));
}

// ─── SectorFlags ─────────────────────────────────────────────────────────────
// Bit-field describing per-sector properties.

enum class SectorFlags : u32
{
    None           = 0,
    Outdoors       = 1u << 0,  ///< Sky visible; no ceiling rendered.
    Underwater     = 1u << 1,  ///< Applies underwater fog and swim physics.
    DamageZone     = 1u << 2,  ///< Entities within take periodic damage.
    TriggerZone    = 1u << 3,  ///< Fires a trigger event on enter/exit.
    // ── Phase 1F additions ────────────────────────────────────────────────────
    HasHeightfield = 1u << 4,  ///< Floor uses heightfield terrain mesh (Phase 1F-D).
                               ///< Set automatically by the editor; do not set manually.
    MovingSector   = 1u << 5,  ///< Sector has runtime motion applied (Phase 2).
                               ///< The game layer writes a SectorMotion offset each tick.
};

[[nodiscard]] inline constexpr SectorFlags operator|(SectorFlags a, SectorFlags b) noexcept
{
    return static_cast<SectorFlags>(static_cast<u32>(a) | static_cast<u32>(b));
}

[[nodiscard]] inline constexpr SectorFlags operator&(SectorFlags a, SectorFlags b) noexcept
{
    return static_cast<SectorFlags>(static_cast<u32>(a) & static_cast<u32>(b));
}

[[nodiscard]] inline constexpr bool hasFlag(SectorFlags flags, SectorFlags test) noexcept
{
    return (flags & test) != SectorFlags::None;
}

// ─── FloorShape ───────────────────────────────────────────────────────────────
// Controls how a sector's floor mesh is generated by the tessellator.
// The ceiling is always flat (or sloped via per-vertex ceilHeightOverride).

enum class FloorShape : u32
{
    Flat         = 0,  ///< Flat (or per-vertex sloped) surface — default, current behaviour.
    Heightfield  = 1,  ///< Terrain mesh from a HeightfieldFloor sample grid (Phase 1F-D).
    VisualStairs = 2,  ///< Stair-step mesh (tread + riser quads) from a StairProfile.
                       ///< Physics collision uses the equivalent linear ramp.
};

// ─── StairProfile ─────────────────────────────────────────────────────────────
// Parameters for FloorShape::VisualStairs tessellation.
//
// The stair run starts at the sector's floorHeight and rises by
// stepCount × riserHeight total, directed along directionAngle in the XZ plane.
// The tessellator clips the sector polygon at each step's tread depth slab to
// correctly bound the treads for any sector shape.

struct StairProfile
{
    u32 stepCount      = 4;     ///< Number of steps.
    f32 riserHeight    = 0.25f; ///< Height of each step riser (world units).
    f32 treadDepth     = 0.5f;  ///< Horizontal depth of each step tread (world units).
    f32 directionAngle = 0.0f;  ///< Direction of the stair run in the XZ plane
                                ///< (radians CCW from world +X axis).
};

} // namespace daedalus::world
